name: Develop PR - build test

on:
  pull_request:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      -
        name: Test
        run: |
          just test

      -
        name: Build
        run: |
          just build-binary

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'

      -
        name: Build
        run: |
          cd ui && just build-local
